/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./src/presentation/components/Body.vue')['default']
    BodyJournalDot: typeof import('./src/presentation/components/BodyJournalDot.vue')['default']
    BodyJournalEntry: typeof import('./src/presentation/components/BodyJournalEntry.vue')['default']
    CancelButton: typeof import('./src/presentation/components/CancelButton.vue')['default']
    ConfirmButton: typeof import('./src/presentation/components/ConfirmButton.vue')['default']
    EntryDisplay: typeof import('./src/presentation/components/EntryDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
